# Generated by Django 6.1.1 on 2026-10-06 05:23

import csv
from pathlib import Path

from django.db import migrations, models, transaction

from baseball.data_loader import stable_id
from baseball.stadium_guides import parking_values


def seed_guides(apps, schema_editor):
    roots = (Path("/data"), Path(__file__).resolve().parents[3] / "data")
    root = next((root for root in roots if (root / "preprocessed/stadium_coordinates.csv").is_file()), None)
    if root is None:
        raise FileNotFoundError(f"Stadium guide CSV not found in {roots}")
    alias = schema_editor.connection.alias
    Stadium = apps.get_model("baseball", "Stadium")
    SeatMap = apps.get_model("baseball", "SeatMap")
    Asset = apps.get_model("baseball", "SeatMapAsset")
    with transaction.atomic(using=alias):
        with (root / "preprocessed/stadium_coordinates.csv").open(encoding="utf-8-sig", newline="") as stream:
            for row in csv.DictReader(stream):
                Stadium.objects.using(alias).filter(stadium_code=row["stadium_code"]).update(**parking_values(row, Stadium))
        with (root / "preprocessed/구장좌석도.csv").open(encoding="utf-8-sig", newline="") as stream:
            for row in csv.DictReader(stream):
                if not row.get("local_asset_url"):
                    continue
                seat = SeatMap.objects.using(alias).filter(
                    home_context__season=int(row["season"]), home_context__team__team_code=row["team_code"],
                    home_context__stadium__stadium_code=row["stadium_code"], map_title=row["map_title"],
                ).get()
                key = f'{row["season"]}:{row["team_code"]}:{row["stadium_code"]}:local-diagram'
                asset, created = Asset.objects.using(alias).get_or_create(seat_map=seat, asset_no=3, defaults={
                    "id": stable_id(Asset, key), "asset_url": row["local_asset_url"],
                    "asset_role": "LOCAL_DIAGRAM", "source_url": row["local_source_url"] or None,
                })
                if not created and (asset.asset_url != row["local_asset_url"] or asset.asset_role != "LOCAL_DIAGRAM"):
                    raise ValueError(f"Existing seat-map asset slot is occupied: {seat.pk}:3")


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0008_stadium_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmapasset',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_captured_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_credit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_kind',
            field=models.CharField(blank=True, choices=[('entrance', 'entrance'), ('preferred-area', 'preferred-area'), ('nearby-alternatives', 'nearby-alternatives'), ('access-gates', 'access-gates')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_visual_notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='parking_map_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(seed_guides, migrations.RunPython.noop),
    ]
