# Generated by Django 6.1.1 on 2026-09-25 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_chat_progress_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('started', '시작'), ('completed', '완료'), ('failed', '실패')], default='started', max_length=12)),
                ('arguments', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('truncated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='chatprogressevent',
            name='unique_chat_progress_sequence',
        ),
        migrations.RemoveField(
            model_name='chatturn',
            name='assistant_message',
        ),
        migrations.RemoveField(
            model_name='chatturn',
            name='human_message',
        ),
        migrations.RemoveField(
            model_name='chatturn',
            name='session',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='guest',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', '사용자'), ('assistant', 'AI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sequence_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('pending', '진행 중'), ('completed', '완료'), ('failed', '실패'), ('stopped', '중단')], default='completed', max_length=12),
        ),
        # ponytail: bigint(id) -> uuid(id) 는 Postgres가 캐스팅을 그냥 거부한다
        # (cannot cast type bigint to uuid), 행이 0개인 빈 테이블에도 똑같이 막힌다.
        # llm_chatmessage.session_id FK 도 같이 bigint -> uuid 로 바꿔야 해서 RunSQL 로
        # FK 를 내리고 두 컬럼을 uuid 로 바꾼 뒤 FK 를 다시 건다.
        # 반드시 빈 테이블(새로 만든 DB)에서만 돌린다 - 기존 행이 있으면 전부 사라진다.
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "llm_chatmessage" DROP CONSTRAINT "llm_chatmessage_session_id_63b50114_fk_llm_chatsession_id"',
                'ALTER TABLE "llm_chatsession" ALTER COLUMN "id" DROP IDENTITY IF EXISTS',
                'ALTER TABLE "llm_chatsession" ALTER COLUMN "id" TYPE uuid USING gen_random_uuid()',
                'ALTER TABLE "llm_chatmessage" ALTER COLUMN "session_id" TYPE uuid USING gen_random_uuid()',
                'ALTER TABLE "llm_chatmessage" ADD CONSTRAINT "llm_chatmessage_session_id_63b50114_fk_llm_chatsession_id"'
                ' FOREIGN KEY ("session_id") REFERENCES "llm_chatsession" ("id") DEFERRABLE INITIALLY DEFERRED',
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='chatsession',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_no'), name='unique_active_message_sequence'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='chat_session_has_one_owner'),
        ),
        migrations.AddField(
            model_name='chattoolcall',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='llm.chatmessage'),
        ),
        migrations.DeleteModel(
            name='ChatProgressEvent',
        ),
        migrations.DeleteModel(
            name='ChatTurn',
        ),
    ]
