# Generated by Django 6.1.1 on 2026-09-30 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_chat_thread_deletion_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.UUIDField(blank=True, null=True, unique=True)),
                ('period', models.CharField(max_length=16)),
                ('used_tokens', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(null=True)),
                ('period', models.CharField(max_length=16)),
                ('status', models.CharField(default='reserved', max_length=16)),
                ('reserved_tokens', models.BigIntegerField()),
                ('charged_tokens', models.BigIntegerField(default=0)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('calls', models.IntegerField(default=0)),
                ('unknown_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='llm.usagewallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usagewallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='usage_wallet_has_one_owner'),
        ),
        migrations.AddIndex(
            model_name='usagecharge',
            index=models.Index(fields=['wallet', 'status'], name='usage_charge_wallet_status'),
        ),
    ]
