# Generated by Django 6.1.1 on 2026-10-02 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0010_usage_wallet_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=255)),
                ('message_id', models.PositiveBigIntegerField()),
                ('rating', models.CharField(choices=[('up', '좋아요'), ('down', '아쉬워요')], max_length=4)),
                ('reason', models.CharField(blank=True, max_length=24)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='llm.chatsession')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'answer_id'), name='feedback_session_answer_unique'), models.CheckConstraint(condition=models.Q(('rating__in', ['up', 'down'])), name='feedback_valid_rating')],
            },
        ),
    ]
