# Generated by Django 6.1.1 on 2026-10-06 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0011_answerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachmentDeletion',
            fields=[
                ('object_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'image'), ('text', 'text'), ('url', 'url')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('object_key', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='llm.chatsession')),
            ],
        ),
    ]
