# Generated by Django 6.1.1 on 2026-10-01 08:22

import ads.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0010_merge_content_doc_tourismplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.CharField(max_length=120, verbose_name='광고주')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='설명')),
                ('image_url', models.URLField(max_length=1000, validators=[ads.models.validate_ad_url], verbose_name='이미지 URL')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='이미지 설명')),
                ('destination_url', models.URLField(max_length=1000, validators=[ads.models.validate_ad_url], verbose_name='이동 URL')),
                ('button_label', models.CharField(default='자세히 보기', max_length=40, verbose_name='버튼 문구')),
                ('context_label', models.CharField(blank=True, max_length=120, verbose_name='지역·분류')),
                ('placement', models.CharField(choices=[('home-club-banner', '홈 구단 광고'), ('home-route-partner-banner', '홈 음식점·시설 광고')], max_length=40, verbose_name='위치')),
                ('starts_at', models.DateTimeField(verbose_name='시작 일시')),
                ('ends_at', models.DateTimeField(verbose_name='종료 일시')),
                ('active', models.BooleanField(default=False, verbose_name='활성')),
                ('is_test', models.BooleanField(default=False, verbose_name='테스트 광고')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='우선순위')),
                ('team_code', models.CharField(blank=True, max_length=10, verbose_name='구단 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='advertisements', to='travel.course', verbose_name='노출 대상 코스')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.place', verbose_name='제휴 장소')),
            ],
            options={
                'ordering': ('-priority', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('exposure_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('impression', '노출'), ('click', '클릭')], max_length=20)),
                ('placement', models.CharField(choices=[('home-club-banner', '홈 구단 광고'), ('home-route-partner-banner', '홈 음식점·시설 광고')], max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ads.adcreative')),
            ],
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['placement', 'active', 'starts_at', 'ends_at'], name='ads_delivery_lookup'),
        ),
        migrations.AddConstraint(
            model_name='adcreative',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ads_valid_period'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['ad', 'kind', 'received_at'], name='ads_event_report'),
        ),
        migrations.AddConstraint(
            model_name='adevent',
            constraint=models.UniqueConstraint(fields=('exposure_id', 'kind'), name='ads_unique_exposure_kind'),
        ),
    ]
